version: '3.8'
services:
  couchdb:
    image: couchdb:3
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: pass
    ports:
      - "5984:5984"
    volumes:
      - couchdata:/opt/couchdb/data

volumes:
  couchdata:
